version: '3'
services:
  monitor_me:
    container_name: "monitor_me"
    build:
      context: "."
    ports:
     - "5000:5000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ".:/app/configdir"
    command:
      - "--config.file=/app/configdir/prometheus.yml"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

