{
 "title": "Monitor Me Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Detail", "type": "text", "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 }, "content": "# Demo App statistics" },
  {
   "title": "Monitor Me Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(up)" }
   ]
  },
  {
   "title": "Average number of seconds a request took",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(flask_http_request_duration_seconds_bucket) "
    }
   ]
  },
  {
   "title": "Requests to Demo App",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count"
    }
   ]
  }
 ]
}